[package]
name = "cart"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
nonmax = "0.5.0"
ufmt = "0.1.0"
wee_alloc = { version = "0.4.5" }

[profile.release]
opt-level = "z"
lto = true
